SET NOCOUNT ON;
-- LTV codes/counts for the two flagged localities (by name)
SELECT LOCALITY_CODE, LOCALITYNAME, COUNT(*) AS ltv_voters
FROM Historic.dbo.LTV2026_Ref
WHERE LOCALITYNAME LIKE '%COVINGTON%' OR LOCALITYNAME LIKE '%SUSSEX%'
GROUP BY LOCALITY_CODE, LOCALITYNAME
ORDER BY LOCALITYNAME;

-- What LTV localities carry codes 580 (Covington FIPS) / 183 (Sussex FIPS) and the
-- codes the join actually used?
SELECT LOCALITY_CODE, LOCALITYNAME, COUNT(*) AS ltv_voters
FROM Historic.dbo.LTV2026_Ref
WHERE LOCALITY_CODE IN ('580','183','053','052')
GROUP BY LOCALITY_CODE, LOCALITYNAME
ORDER BY LOCALITY_CODE;
