SET NOCOUNT ON;
SELECT COUNT(*) AS total_rows FROM Historic.dbo.LTV2026_Ref;
SELECT ABSENTEE, COUNT(*) AS c FROM Historic.dbo.LTV2026_Ref GROUP BY ABSENTEE ORDER BY c DESC;
SELECT COUNT(*) AS leftover_quote_rows FROM Historic.dbo.LTV2026_Ref
  WHERE LAST_NAME LIKE '%"%' OR FIRST_NAME LIKE '%"%' OR LOCALITYNAME LIKE '%"%';
SELECT TOP 3 IDENTIFICATION_NUMBER, LAST_NAME, FIRST_NAME, LOCALITYNAME, DOB, ABSENTEE
  FROM Historic.dbo.LTV2026_Ref;
SELECT TOP 5 LAST_NAME, FIRST_NAME FROM Historic.dbo.LTV2026_Ref
  WHERE LAST_NAME LIKE '%[^ -~]%' OR FIRST_NAME LIKE '%[^ -~]%';
