-- LTV2026_Ref_table.sql
-- DDL for Historic.dbo.LTV2026_Ref
-- Source: C:\Temp\SBE\LTWV\LTV2026_Ref.csv  (SBE "List of Those Who Voted",
--         April 21, 2026 Virginia Constitutional Amendment Referendum)
-- Raw load: all 50 columns NVARCHAR(255). Schema matches Historic.dbo.LTV2025_GEN.
-- Loader: C:\Scripts\Python\Python_LTWV\load_LTV2026_Ref.py

IF OBJECT_ID('Historic.dbo.LTV2026_Ref','U') IS NOT NULL
    DROP TABLE Historic.dbo.LTV2026_Ref;
GO

CREATE TABLE dbo.LTV2026_Ref (
  [INV_NO] NVARCHAR(255),
  [ELECTION_DATE] NVARCHAR(255),
  [ELECTION_NAME] NVARCHAR(255),
  [ELECTION_YEAR] NVARCHAR(255),
  [ELECTION_TYPE] NVARCHAR(255),
  [PRIMARY_TYPE_CODE_NAME] NVARCHAR(255),
  [IDENTIFICATION_NUMBER] NVARCHAR(255),
  [LAST_NAME] NVARCHAR(255),
  [FIRST_NAME] NVARCHAR(255),
  [MIDDLE_NAME] NVARCHAR(255),
  [SUFFIX] NVARCHAR(255),
  [HOUSE_NUMBER] NVARCHAR(255),
  [HOUSENUMBERSUFFIX] NVARCHAR(255),
  [STREET_NAME] NVARCHAR(255),
  [STREETTYPECODENAME] NVARCHAR(255),
  [DIRECTION] NVARCHAR(255),
  [POST_DIRECTION] NVARCHAR(255),
  [APT_NUM] NVARCHAR(255),
  [CITY] NVARCHAR(255),
  [STATE] NVARCHAR(255),
  [ZIP] NVARCHAR(255),
  [ADDRESS_LINE_1] NVARCHAR(255),
  [ADDRESS_LINE_2] NVARCHAR(255),
  [ADDRESS_LINE_3] NVARCHAR(255),
  [LOCALITY_CODE] NVARCHAR(255),
  [LOCALITYNAME] NVARCHAR(255),
  [PRECINCT_CODE_VALUE] NVARCHAR(255),
  [PRECINCTNAME] NVARCHAR(255),
  [TOWNNAME_CODE_VALUE] NVARCHAR(255),
  [TOWNNAME_CODE_NAME] NVARCHAR(255),
  [TOWNPREC_CODE_VALUE] NVARCHAR(255),
  [TOWNPREC_CODE_NAME] NVARCHAR(255),
  [CONG_CODE_VALUE] NVARCHAR(255),
  [STSENATE_CODE_VALUE] NVARCHAR(255),
  [STHOUSE_CODE_VALUE] NVARCHAR(255),
  [GENDER] NVARCHAR(255),
  [DOB] NVARCHAR(255),
  [REGISTRATION_DATE] NVARCHAR(255),
  [EFFECTIVE_DATE] NVARCHAR(255),
  [MAILING_ADDRESS_LINE_1] NVARCHAR(255),
  [MAILING_ADDRESS_LINE_2] NVARCHAR(255),
  [MAILING_ADDRESS_LINE_3] NVARCHAR(255),
  [MAILING_CITY] NVARCHAR(255),
  [MAILING_STATE] NVARCHAR(255),
  [MAILING_ZIP] NVARCHAR(255),
  [SUPERDIST_CODE_VALUE] NVARCHAR(255),
  [SUPERDIST_CODE_NAME] NVARCHAR(255),
  [MAILING_ADDRESS_USE_RESIDENCE] NVARCHAR(255),
  [STATUS] NVARCHAR(255),
  [ABSENTEE] NVARCHAR(255)
);
GO
